//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDienThoai {
    
    
    public partial class MasterPage1 {
        
        /// <summary>
        /// FormMaster1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm FormMaster1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// UC_Banner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShopDienThoai.Controls.UC_Banner UC_Banner;
        
        /// <summary>
        /// UC_Menu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShopDienThoai.Controls.UC_Menu UC_Menu;
        
        /// <summary>
        /// UC_TimKiemDienThoai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShopDienThoai.Controls.UC_TimKiemDienThoai UC_TimKiemDienThoai;
        
        /// <summary>
        /// UC_CacHangDienThoai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShopDienThoai.Controls.UC_CacHangDienThoai UC_CacHangDienThoai;
        
        /// <summary>
        /// UC_SoSanhDienThoai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShopDienThoai.Controls.UC_SoSanhDienThoai UC_SoSanhDienThoai;
        
        /// <summary>
        /// UC_GioHangNho control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShopDienThoai.Controls.UC_GioHangNho UC_GioHangNho;
        
        /// <summary>
        /// MainContaint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContaint;
        
        /// <summary>
        /// UC_TimTheoTinhNang control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShopDienThoai.Controls.UC_TimTheoTinhNang UC_TimTheoTinhNang;
        
        /// <summary>
        /// UC_DienThoaiBanChay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShopDienThoai.Controls.UC_DienThoaiBanChay UC_DienThoaiBanChay;
        
        /// <summary>
        /// UC_HoTroTrucTuyen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ShopDienThoai.Controls.UC_HoTroTrucTuyen UC_HoTroTrucTuyen;
    }
}
